# Generated by Django 6.0.4 on 2026-04-19 12:13

import trainee.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='name',
            field=models.CharField(max_length=100, validators=[trainee.models.validate_name_length]),
        ),
    ]
